# This is a basic workflow to help you get started with Actions

name: lambda-version-publish-appversion2

on:
  workflow_run:
    workflows: ["lambda-version-deploy-appversion2"]   # Name of the workflow in bootstrap.yml
    branches:
      - main
    types:
      - completed           # Triggers after bootstrap completes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # integration with OIDC recommended
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # integration with OIDC recommended
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Wait for Lambda updation to finish
        run: |
            STATE=$(aws lambda get-function \
              --function-name canary-appversion2 \
              --query 'Configuration.State' \
              --output text)
            LASTUPDATE=$(aws lambda get-function \
              --function-name canary-appversion2 \
              --query 'Configuration.LastUpdateStatus' \
              --output text)
            echo "State: $STATE, LastUpdateStatus: $LASTUPDATE"
            if [ "$STATE" = "Active" ] && [ "$LASTUPDATE" = "Successful" ]; then
              sleep 30
              break
            fi

      - name: Check if Lambda function exists
        run: |
          set +e
          aws lambda get-function --function-name canary-appversion2
          echo "existslambda=$?" >> $GITHUB_ENV


      - name: Publish for appversion2
        if: env.existslambda == '0'  # Runs only if get-function exists
        run: |
          aws lambda publish-version \
            --function-name canary-appversion1 --description "version of appversion2"