# This is a basic workflow to help you get started with Actions

name: lambda-version-publish-appversion1

on:
  workflow_run:
    workflows: ["lambda-version-deploy-appversion1"]   # Name of the workflow in bootstrap.yml
    branches:
      - main
    types:
      - completed           # Triggers after bootstrap completes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # integration with OIDC recommended
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # integration with OIDC recommended
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Publish Version for appversion1
#        if: env.existslambda == '254'  # Runs only if get-function failed (version1 does not exist)
        run: |
          aws lambda publish-version \
            --function-name canary-appversion1 --description "version of appversion1"
